[project]
name = "scorer-has"
version = "0.1.0"
description = "Human Authenticity Score (HAS) algorithm"
requires-python = ">=3.12"
dependencies = [
    "scorer-utils",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/scorer_has"]
